import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Banner from "./components/banner/Banner";
import Titulo from "./components/titulo/Titulo";
import Navegacao from "./components/Navegacao/Navegacao";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Banner>
          <div className="flex-1 text-center">
            <Titulo title="Blog Espaçonaves" className="text-4xl" />
          </div>
          <div className="flex gap-3 pr-5">
            <Navegacao
              caminho="/"
              txt="Home"
              className="hover:text-yellow-300"
            />
            |
            <Navegacao
              caminho="/espaconaves"
              txt="Espaçonaves"
              className="hover:text-yellow-300"
            />
            |
            <Navegacao
              caminho="/categorias"
              txt="Categorias"
              className="hover:text-yellow-300"
            />
          </div>
        </Banner>
        {children}
      </body>
    </html>
  );
}
